---
all:
  vars:
    ansible_user: ubuntu 
    ansible_python_interpreter: /usr/bin/python3
  children:  
    sipgates:
      hosts:
        sipgate:
          ansible_host: turn.bravo
      vars: 
        public_ip: "{{ ansible_default_ipv4.address }}"
        public_fqdn: "{{ ansible_host }}"
        public_hostname: "{{ ansible_hostname }}"
