- name: Copy timesyncd.conf  /etc/systemd/timesyncd.conf
  template:
    src: timesyncd.conf
    dest: /etc/systemd
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify:
  - "restart timesyncd"

- name: set timezone to UTC
  timezone:
    name: Etc/UTC
